//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirMVC.ServiceReferenceAmimir {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ESTADO_LISTA_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ESTADO_LISTA_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ESTADO_GUARDAR_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ESTADO_GUARDAR_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ESTADO_EDITAR_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ESTADO_EDITAR_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ANIME_LISTA_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ANIME_LISTA_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EstadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEstrenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PopularidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EstadoID {
            get {
                return this.EstadoIDField;
            }
            set {
                if ((this.EstadoIDField.Equals(value) != true)) {
                    this.EstadoIDField = value;
                    this.RaisePropertyChanged("EstadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEstreno {
            get {
                return this.FechaEstrenoField;
            }
            set {
                if ((this.FechaEstrenoField.Equals(value) != true)) {
                    this.FechaEstrenoField = value;
                    this.RaisePropertyChanged("FechaEstreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Popularidad {
            get {
                return this.PopularidadField;
            }
            set {
                if ((this.PopularidadField.Equals(value) != true)) {
                    this.PopularidadField = value;
                    this.RaisePropertyChanged("Popularidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Precuela {
            get {
                return this.PrecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecuelaField, value) != true)) {
                    this.PrecuelaField = value;
                    this.RaisePropertyChanged("Precuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrecuelaID {
            get {
                return this.PrecuelaIDField;
            }
            set {
                if ((this.PrecuelaIDField.Equals(value) != true)) {
                    this.PrecuelaIDField = value;
                    this.RaisePropertyChanged("PrecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secuela {
            get {
                return this.SecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuelaField, value) != true)) {
                    this.SecuelaField = value;
                    this.RaisePropertyChanged("Secuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecuelaID {
            get {
                return this.SecuelaIDField;
            }
            set {
                if ((this.SecuelaIDField.Equals(value) != true)) {
                    this.SecuelaIDField = value;
                    this.RaisePropertyChanged("SecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ANIME_GUARDAR_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ANIME_GUARDAR_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEstrenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PopularidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoID {
            get {
                return this.EstadoIDField;
            }
            set {
                if ((this.EstadoIDField.Equals(value) != true)) {
                    this.EstadoIDField = value;
                    this.RaisePropertyChanged("EstadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEstreno {
            get {
                return this.FechaEstrenoField;
            }
            set {
                if ((this.FechaEstrenoField.Equals(value) != true)) {
                    this.FechaEstrenoField = value;
                    this.RaisePropertyChanged("FechaEstreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Popularidad {
            get {
                return this.PopularidadField;
            }
            set {
                if ((this.PopularidadField.Equals(value) != true)) {
                    this.PopularidadField = value;
                    this.RaisePropertyChanged("Popularidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Precuela {
            get {
                return this.PrecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecuelaField, value) != true)) {
                    this.PrecuelaField = value;
                    this.RaisePropertyChanged("Precuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrecuelaID {
            get {
                return this.PrecuelaIDField;
            }
            set {
                if ((this.PrecuelaIDField.Equals(value) != true)) {
                    this.PrecuelaIDField = value;
                    this.RaisePropertyChanged("PrecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secuela {
            get {
                return this.SecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuelaField, value) != true)) {
                    this.SecuelaField = value;
                    this.RaisePropertyChanged("Secuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecuelaID {
            get {
                return this.SecuelaIDField;
            }
            set {
                if ((this.SecuelaIDField.Equals(value) != true)) {
                    this.SecuelaIDField = value;
                    this.RaisePropertyChanged("SecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_ANIME_EDITAR_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_ANIME_EDITAR_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EstadoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaEstrenoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PopularidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PrecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PuntuacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecuelaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SecuelaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EstadoID {
            get {
                return this.EstadoIDField;
            }
            set {
                if ((this.EstadoIDField.Equals(value) != true)) {
                    this.EstadoIDField = value;
                    this.RaisePropertyChanged("EstadoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaEstreno {
            get {
                return this.FechaEstrenoField;
            }
            set {
                if ((this.FechaEstrenoField.Equals(value) != true)) {
                    this.FechaEstrenoField = value;
                    this.RaisePropertyChanged("FechaEstreno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Popularidad {
            get {
                return this.PopularidadField;
            }
            set {
                if ((this.PopularidadField.Equals(value) != true)) {
                    this.PopularidadField = value;
                    this.RaisePropertyChanged("Popularidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Precuela {
            get {
                return this.PrecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.PrecuelaField, value) != true)) {
                    this.PrecuelaField = value;
                    this.RaisePropertyChanged("Precuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PrecuelaID {
            get {
                return this.PrecuelaIDField;
            }
            set {
                if ((this.PrecuelaIDField.Equals(value) != true)) {
                    this.PrecuelaIDField = value;
                    this.RaisePropertyChanged("PrecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Puntuacion {
            get {
                return this.PuntuacionField;
            }
            set {
                if ((this.PuntuacionField.Equals(value) != true)) {
                    this.PuntuacionField = value;
                    this.RaisePropertyChanged("Puntuacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Secuela {
            get {
                return this.SecuelaField;
            }
            set {
                if ((object.ReferenceEquals(this.SecuelaField, value) != true)) {
                    this.SecuelaField = value;
                    this.RaisePropertyChanged("Secuela");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SecuelaID {
            get {
                return this.SecuelaIDField;
            }
            set {
                if ((this.SecuelaIDField.Equals(value) != true)) {
                    this.SecuelaIDField = value;
                    this.RaisePropertyChanged("SecuelaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_CAPITULO_LISTA_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_CAPITULO_LISTA_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnimeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPublicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anime {
            get {
                return this.AnimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimeField, value) != true)) {
                    this.AnimeField = value;
                    this.RaisePropertyChanged("Anime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnimeID {
            get {
                return this.AnimeIDField;
            }
            set {
                if ((this.AnimeIDField.Equals(value) != true)) {
                    this.AnimeIDField = value;
                    this.RaisePropertyChanged("AnimeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((this.DuracionField.Equals(value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPublicado {
            get {
                return this.FechaPublicadoField;
            }
            set {
                if ((this.FechaPublicadoField.Equals(value) != true)) {
                    this.FechaPublicadoField = value;
                    this.RaisePropertyChanged("FechaPublicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STPR_CAPITULO_GUARDAR_Result", Namespace="http://schemas.datacontract.org/2004/07/AmimirWCF")]
    [System.SerializableAttribute()]
    public partial class STPR_CAPITULO_GUARDAR_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnimeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DuracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPublicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SinopsisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string URLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Anime {
            get {
                return this.AnimeField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimeField, value) != true)) {
                    this.AnimeField = value;
                    this.RaisePropertyChanged("Anime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnimeID {
            get {
                return this.AnimeIDField;
            }
            set {
                if ((this.AnimeIDField.Equals(value) != true)) {
                    this.AnimeIDField = value;
                    this.RaisePropertyChanged("AnimeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Duracion {
            get {
                return this.DuracionField;
            }
            set {
                if ((this.DuracionField.Equals(value) != true)) {
                    this.DuracionField = value;
                    this.RaisePropertyChanged("Duracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPublicado {
            get {
                return this.FechaPublicadoField;
            }
            set {
                if ((this.FechaPublicadoField.Equals(value) != true)) {
                    this.FechaPublicadoField = value;
                    this.RaisePropertyChanged("FechaPublicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sinopsis {
            get {
                return this.SinopsisField;
            }
            set {
                if ((object.ReferenceEquals(this.SinopsisField, value) != true)) {
                    this.SinopsisField = value;
                    this.RaisePropertyChanged("Sinopsis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string URL {
            get {
                return this.URLField;
            }
            set {
                if ((object.ReferenceEquals(this.URLField, value) != true)) {
                    this.URLField = value;
                    this.RaisePropertyChanged("URL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceAmimir.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoLista", ReplyAction="http://tempuri.org/IService1/estadoListaResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result[] estadoLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoLista", ReplyAction="http://tempuri.org/IService1/estadoListaResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result[]> estadoListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoGuardar", ReplyAction="http://tempuri.org/IService1/estadoGuardarResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_GUARDAR_Result estadoGuardar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoGuardar", ReplyAction="http://tempuri.org/IService1/estadoGuardarResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_GUARDAR_Result> estadoGuardarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoDatos", ReplyAction="http://tempuri.org/IService1/estadoDatosResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result estadoDatos(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoDatos", ReplyAction="http://tempuri.org/IService1/estadoDatosResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result> estadoDatosAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoEditar", ReplyAction="http://tempuri.org/IService1/estadoEditarResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_EDITAR_Result estadoEditar(int ID, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoEditar", ReplyAction="http://tempuri.org/IService1/estadoEditarResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_EDITAR_Result> estadoEditarAsync(int ID, string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoBorrar", ReplyAction="http://tempuri.org/IService1/estadoBorrarResponse")]
        void estadoBorrar(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/estadoBorrar", ReplyAction="http://tempuri.org/IService1/estadoBorrarResponse")]
        System.Threading.Tasks.Task estadoBorrarAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeLista", ReplyAction="http://tempuri.org/IService1/animeListaResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result[] animeLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeLista", ReplyAction="http://tempuri.org/IService1/animeListaResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result[]> animeListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeGuardar", ReplyAction="http://tempuri.org/IService1/animeGuardarResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_GUARDAR_Result animeGuardar(string Nombre, System.Nullable<System.DateTime> FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeGuardar", ReplyAction="http://tempuri.org/IService1/animeGuardarResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_GUARDAR_Result> animeGuardarAsync(string Nombre, System.Nullable<System.DateTime> FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeDatos", ReplyAction="http://tempuri.org/IService1/animeDatosResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result animeDatos(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeDatos", ReplyAction="http://tempuri.org/IService1/animeDatosResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result> animeDatosAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeEditar", ReplyAction="http://tempuri.org/IService1/animeEditarResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_EDITAR_Result animeEditar(int ID, string Nombre, System.DateTime FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeEditar", ReplyAction="http://tempuri.org/IService1/animeEditarResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_EDITAR_Result> animeEditarAsync(int ID, string Nombre, System.DateTime FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeBorrar", ReplyAction="http://tempuri.org/IService1/animeBorrarResponse")]
        void animeBorrar(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/animeBorrar", ReplyAction="http://tempuri.org/IService1/animeBorrarResponse")]
        System.Threading.Tasks.Task animeBorrarAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capituloLista", ReplyAction="http://tempuri.org/IService1/capituloListaResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_LISTA_Result[] capituloLista();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capituloLista", ReplyAction="http://tempuri.org/IService1/capituloListaResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_LISTA_Result[]> capituloListaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capituloGuardar", ReplyAction="http://tempuri.org/IService1/capituloGuardarResponse")]
        AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_GUARDAR_Result capituloGuardar(int AnimeID, string Titulo, int Duracion, string Sinopsis, int Orden, string FechaPublicado, string URL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/capituloGuardar", ReplyAction="http://tempuri.org/IService1/capituloGuardarResponse")]
        System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_GUARDAR_Result> capituloGuardarAsync(int AnimeID, string Titulo, int Duracion, string Sinopsis, int Orden, string FechaPublicado, string URL);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : AmimirMVC.ServiceReferenceAmimir.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<AmimirMVC.ServiceReferenceAmimir.IService1>, AmimirMVC.ServiceReferenceAmimir.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result[] estadoLista() {
            return base.Channel.estadoLista();
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result[]> estadoListaAsync() {
            return base.Channel.estadoListaAsync();
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_GUARDAR_Result estadoGuardar(string nombre) {
            return base.Channel.estadoGuardar(nombre);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_GUARDAR_Result> estadoGuardarAsync(string nombre) {
            return base.Channel.estadoGuardarAsync(nombre);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result estadoDatos(int ID) {
            return base.Channel.estadoDatos(ID);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_LISTA_Result> estadoDatosAsync(int ID) {
            return base.Channel.estadoDatosAsync(ID);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_EDITAR_Result estadoEditar(int ID, string nombre) {
            return base.Channel.estadoEditar(ID, nombre);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ESTADO_EDITAR_Result> estadoEditarAsync(int ID, string nombre) {
            return base.Channel.estadoEditarAsync(ID, nombre);
        }
        
        public void estadoBorrar(int ID) {
            base.Channel.estadoBorrar(ID);
        }
        
        public System.Threading.Tasks.Task estadoBorrarAsync(int ID) {
            return base.Channel.estadoBorrarAsync(ID);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result[] animeLista() {
            return base.Channel.animeLista();
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result[]> animeListaAsync() {
            return base.Channel.animeListaAsync();
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_GUARDAR_Result animeGuardar(string Nombre, System.Nullable<System.DateTime> FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID) {
            return base.Channel.animeGuardar(Nombre, FechaEstreno, SecuelaID, PrecuelaID, Sinopsis, Puntuacion, Popularidad, EstadoID);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_GUARDAR_Result> animeGuardarAsync(string Nombre, System.Nullable<System.DateTime> FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID) {
            return base.Channel.animeGuardarAsync(Nombre, FechaEstreno, SecuelaID, PrecuelaID, Sinopsis, Puntuacion, Popularidad, EstadoID);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result animeDatos(int ID) {
            return base.Channel.animeDatos(ID);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_LISTA_Result> animeDatosAsync(int ID) {
            return base.Channel.animeDatosAsync(ID);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_EDITAR_Result animeEditar(int ID, string Nombre, System.DateTime FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID) {
            return base.Channel.animeEditar(ID, Nombre, FechaEstreno, SecuelaID, PrecuelaID, Sinopsis, Puntuacion, Popularidad, EstadoID);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_ANIME_EDITAR_Result> animeEditarAsync(int ID, string Nombre, System.DateTime FechaEstreno, System.Nullable<int> SecuelaID, System.Nullable<int> PrecuelaID, string Sinopsis, decimal Puntuacion, decimal Popularidad, int EstadoID) {
            return base.Channel.animeEditarAsync(ID, Nombre, FechaEstreno, SecuelaID, PrecuelaID, Sinopsis, Puntuacion, Popularidad, EstadoID);
        }
        
        public void animeBorrar(int ID) {
            base.Channel.animeBorrar(ID);
        }
        
        public System.Threading.Tasks.Task animeBorrarAsync(int ID) {
            return base.Channel.animeBorrarAsync(ID);
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_LISTA_Result[] capituloLista() {
            return base.Channel.capituloLista();
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_LISTA_Result[]> capituloListaAsync() {
            return base.Channel.capituloListaAsync();
        }
        
        public AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_GUARDAR_Result capituloGuardar(int AnimeID, string Titulo, int Duracion, string Sinopsis, int Orden, string FechaPublicado, string URL) {
            return base.Channel.capituloGuardar(AnimeID, Titulo, Duracion, Sinopsis, Orden, FechaPublicado, URL);
        }
        
        public System.Threading.Tasks.Task<AmimirMVC.ServiceReferenceAmimir.STPR_CAPITULO_GUARDAR_Result> capituloGuardarAsync(int AnimeID, string Titulo, int Duracion, string Sinopsis, int Orden, string FechaPublicado, string URL) {
            return base.Channel.capituloGuardarAsync(AnimeID, Titulo, Duracion, Sinopsis, Orden, FechaPublicado, URL);
        }
    }
}
