//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmimirWCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AmimirEntities : DbContext
    {
        public AmimirEntities()
            : base("name=AmimirEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<STPR_ANIME_LISTA_Result> STPR_ANIME_LISTA_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ANIME_LISTA_Result>("STPR_ANIME_LISTA_Result");
        }
    
        public virtual ObjectResult<STPR_CAPITULO_LISTA_Result> STPR_CAPITULO_LISTA_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_CAPITULO_LISTA_Result>("STPR_CAPITULO_LISTA_Result");
        }
    
        public virtual ObjectResult<STPR_ESTADO_LISTA_Result> STPR_ESTADO_LISTA_Result()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ESTADO_LISTA_Result>("STPR_ESTADO_LISTA_Result");
        }
    
        public virtual int STPR_ANIME_BORRAR_Result(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STPR_ANIME_BORRAR_Result", iDParameter);
        }
    
        public virtual int STPR_CAPITULO_BORRAR_Result(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STPR_CAPITULO_BORRAR_Result", iDParameter);
        }
    
        public virtual ObjectResult<STPR_CAPITULO_EDITAR_Result> STPR_CAPITULO_EDITAR_Result(Nullable<int> iD, Nullable<int> animeID, string titulo, Nullable<int> duracion, string sinopsis, Nullable<int> orden, Nullable<System.DateTime> fechaPublicado, string uRL)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var animeIDParameter = animeID.HasValue ?
                new ObjectParameter("AnimeID", animeID) :
                new ObjectParameter("AnimeID", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("Duracion", duracion) :
                new ObjectParameter("Duracion", typeof(int));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("Sinopsis", sinopsis) :
                new ObjectParameter("Sinopsis", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            var fechaPublicadoParameter = fechaPublicado.HasValue ?
                new ObjectParameter("FechaPublicado", fechaPublicado) :
                new ObjectParameter("FechaPublicado", typeof(System.DateTime));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_CAPITULO_EDITAR_Result>("STPR_CAPITULO_EDITAR_Result", iDParameter, animeIDParameter, tituloParameter, duracionParameter, sinopsisParameter, ordenParameter, fechaPublicadoParameter, uRLParameter);
        }
    
        public virtual ObjectResult<STPR_CAPITULO_GUARDAR_Result> STPR_CAPITULO_GUARDAR_Result(Nullable<int> animeID, string titulo, Nullable<int> duracion, string sinopsis, Nullable<int> orden, Nullable<System.DateTime> fechaPublicado, string uRL)
        {
            var animeIDParameter = animeID.HasValue ?
                new ObjectParameter("AnimeID", animeID) :
                new ObjectParameter("AnimeID", typeof(int));
    
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var duracionParameter = duracion.HasValue ?
                new ObjectParameter("Duracion", duracion) :
                new ObjectParameter("Duracion", typeof(int));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("Sinopsis", sinopsis) :
                new ObjectParameter("Sinopsis", typeof(string));
    
            var ordenParameter = orden.HasValue ?
                new ObjectParameter("Orden", orden) :
                new ObjectParameter("Orden", typeof(int));
    
            var fechaPublicadoParameter = fechaPublicado.HasValue ?
                new ObjectParameter("FechaPublicado", fechaPublicado) :
                new ObjectParameter("FechaPublicado", typeof(System.DateTime));
    
            var uRLParameter = uRL != null ?
                new ObjectParameter("URL", uRL) :
                new ObjectParameter("URL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_CAPITULO_GUARDAR_Result>("STPR_CAPITULO_GUARDAR_Result", animeIDParameter, tituloParameter, duracionParameter, sinopsisParameter, ordenParameter, fechaPublicadoParameter, uRLParameter);
        }
    
        public virtual int STPR_ESTADO_BORRAR_Result(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("STPR_ESTADO_BORRAR_Result", iDParameter);
        }
    
        public virtual ObjectResult<STPR_ESTADO_EDITAR_Result> STPR_ESTADO_EDITAR_Result(Nullable<int> iD, string nombre)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ESTADO_EDITAR_Result>("STPR_ESTADO_EDITAR_Result", iDParameter, nombreParameter);
        }
    
        public virtual ObjectResult<STPR_ESTADO_GUARDAR_Result> STPR_ESTADO_GUARDAR_Result(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ESTADO_GUARDAR_Result>("STPR_ESTADO_GUARDAR_Result", nombreParameter);
        }
    
        public virtual ObjectResult<STPR_ANIME_GUARDAR_Result> STPR_ANIME_GUARDAR_Result(string nombre, Nullable<System.DateTime> fechaEstreno, Nullable<int> secuelaID, Nullable<int> precuelaID, string sinopsis, Nullable<decimal> puntuacion, Nullable<decimal> popularidad, Nullable<int> estadoID)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fechaEstrenoParameter = fechaEstreno.HasValue ?
                new ObjectParameter("FechaEstreno", fechaEstreno) :
                new ObjectParameter("FechaEstreno", typeof(System.DateTime));
    
            var secuelaIDParameter = secuelaID.HasValue ?
                new ObjectParameter("SecuelaID", secuelaID) :
                new ObjectParameter("SecuelaID", typeof(int));
    
            var precuelaIDParameter = precuelaID.HasValue ?
                new ObjectParameter("PrecuelaID", precuelaID) :
                new ObjectParameter("PrecuelaID", typeof(int));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("Sinopsis", sinopsis) :
                new ObjectParameter("Sinopsis", typeof(string));
    
            var puntuacionParameter = puntuacion.HasValue ?
                new ObjectParameter("Puntuacion", puntuacion) :
                new ObjectParameter("Puntuacion", typeof(decimal));
    
            var popularidadParameter = popularidad.HasValue ?
                new ObjectParameter("Popularidad", popularidad) :
                new ObjectParameter("Popularidad", typeof(decimal));
    
            var estadoIDParameter = estadoID.HasValue ?
                new ObjectParameter("EstadoID", estadoID) :
                new ObjectParameter("EstadoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ANIME_GUARDAR_Result>("STPR_ANIME_GUARDAR_Result", nombreParameter, fechaEstrenoParameter, secuelaIDParameter, precuelaIDParameter, sinopsisParameter, puntuacionParameter, popularidadParameter, estadoIDParameter);
        }
    
        public virtual ObjectResult<STPR_ANIME_EDITAR_Result> STPR_ANIME_EDITAR_Result(Nullable<int> iD, string nombre, Nullable<System.DateTime> fechaEstreno, Nullable<int> secuelaID, Nullable<int> precuelaID, string sinopsis, Nullable<decimal> puntuacion, Nullable<decimal> popularidad, Nullable<int> estadoID)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var fechaEstrenoParameter = fechaEstreno.HasValue ?
                new ObjectParameter("FechaEstreno", fechaEstreno) :
                new ObjectParameter("FechaEstreno", typeof(System.DateTime));
    
            var secuelaIDParameter = secuelaID.HasValue ?
                new ObjectParameter("SecuelaID", secuelaID) :
                new ObjectParameter("SecuelaID", typeof(int));
    
            var precuelaIDParameter = precuelaID.HasValue ?
                new ObjectParameter("PrecuelaID", precuelaID) :
                new ObjectParameter("PrecuelaID", typeof(int));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("Sinopsis", sinopsis) :
                new ObjectParameter("Sinopsis", typeof(string));
    
            var puntuacionParameter = puntuacion.HasValue ?
                new ObjectParameter("Puntuacion", puntuacion) :
                new ObjectParameter("Puntuacion", typeof(decimal));
    
            var popularidadParameter = popularidad.HasValue ?
                new ObjectParameter("Popularidad", popularidad) :
                new ObjectParameter("Popularidad", typeof(decimal));
    
            var estadoIDParameter = estadoID.HasValue ?
                new ObjectParameter("EstadoID", estadoID) :
                new ObjectParameter("EstadoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<STPR_ANIME_EDITAR_Result>("STPR_ANIME_EDITAR_Result", iDParameter, nombreParameter, fechaEstrenoParameter, secuelaIDParameter, precuelaIDParameter, sinopsisParameter, puntuacionParameter, popularidadParameter, estadoIDParameter);
        }
    }
}
